const OK = 200
const SUCCESS_CREATED = 201
const NO_CONTENT = 204
const UNAUTHORIZED = 401
const BAD_REQUEST = 400
const NOT_FOUND = 404
const NOT_ALLOWED = 405
const INTERNAL_SERVER_ERROR = 500

module.exports = {
  OK,
  SUCCESS_CREATED,
  NO_CONTENT,
  UNAUTHORIZED,
  BAD_REQUEST,
  NOT_FOUND,
  NOT_ALLOWED,
  INTERNAL_SERVER_ERROR,
}